#!/bin/bash -e

MAGENTO_DIR=$(pwd)

WARDEN_DIR="$(dirname $(pwd))/warden"
WARDEN_BIN="${WARDEN_DIR}/bin/warden"

echo "MAGENTO_DIR: ${MAGENTO_DIR}"

echo "WARDEN_DIR: ${WARDEN_DIR}"
echo "WARDEN_BIN: ${WARDEN_BIN}"

set -x
exit

# fresh clone of warden
rm -rf ${WARDEN_DIR} || true
git clone --depth 1 https://github.com/wardenenv/warden.git ${WARDEN_DIR}

# configure warden
${WARDEN_BIN} env-init magento2 magento2



cp nginx.conf.sample nginx.conf
sed -i '0,/^# PHP entry point for setup application$/d' nginx.conf
sed -i 's/ fastcgi_backend;/ $fastcgi_backend;/g' nginx.conf
line=$(($(grep -n '# PHP entry point for main application' nginx.conf | cut -f1 -d:)-1)); 

echo $line;
head -n $line nginx.conf > nginx.conf.tmp

tee -a nginx.conf.tmp << END
location ~* ^/dev/tests/acceptance/utils($|/) {
  root \$MAGE_ROOT;
  location ~ ^/dev/tests/acceptance/utils/command.php {
      fastcgi_pass   fastcgi_backend;
      fastcgi_index  index.php;
      fastcgi_param  SCRIPT_FILENAME  \$document_root\$fastcgi_script_name;
      include        fastcgi_params;
  }
}
END

tail -n +$line nginx.conf >> nginx.conf.tmp
mv nginx.conf.tmp nginx.conf


https://docs.warden.dev/environments/customizing.html


bin/magento setup:install \
  --backend-frontname=admin \
  --db-host=db \
  --db-name=magento \
  --db-user=magento \
  --db-password=magento \
  --http-cache-hosts=varnish:80 \
  --session-save=redis \
  --session-save-redis-host=redis \
  --session-save-redis-port=6379 \
  --session-save-redis-db=2 \
  --cache-backend=redis \
  --cache-backend-redis-server=redis \
  --cache-backend-redis-db=0 \
  --cache-backend-redis-port=6379 \
  --page-cache=redis \
  --page-cache-redis-server=redis \
  --page-cache-redis-db=1 \
  --page-cache-redis-port=6379 \
  --search-engine=elasticsearch7 \
  --elasticsearch-host=elasticsearch \
  --elasticsearch-port=9200 \
  --elasticsearch-enable-auth=0 \
  --elasticsearch-index-prefix=magento2

# https://github.com/magento/magento2/issues/37236 - unable to install magento with es 8 :(

/workspaces/warden/bin/warden env exec -T php-fpm bin/magento admin:user:create \
  --admin-password="password123" \
  --admin-user="admin" \
  --admin-firstname="Local" \
  --admin-lastname="Admin" \
  --admin-email="admin@example.com"

/workspaces/warden/bin/warden env exec -T php-fpm bin/magento config:set --lock-env web/unsecure/base_url https://adamzero1-vigilant-space-fortnight-gj4grxvv5hwv4v-80.preview.app.github.dev/
/workspaces/warden/bin/warden env exec -T php-fpm bin/magento config:set --lock-env web/secure/base_url https://adamzero1-vigilant-space-fortnight-gj4grxvv5hwv4v-80.preview.app.github.dev/
/workspaces/warden/bin/warden env exec -T php-fpm bin/magento config:set cms/wysiwyg/enabled disabled

/workspaces/warden/bin/warden env exec -T php-fpm bin/magento config:set admin/security/admin_account_sharing 1
/workspaces/warden/bin/warden env exec -T php-fpm bin/magento config:set admin/security/use_form_key 0

/workspaces/warden/bin/warden env exec -T php-fpm bin/magento config:set web/seo/use_rewrites 1


# The "twofactorauth/general/force_providers" path doesn't exist. Verify and try again.
/workspaces/warden/bin/warden env exec -T php-fpm bin/magento config:set twofactorauth/general/force_providers google
/workspaces/warden/bin/warden env exec -T php-fpm bin/magento config:set twofactorauth/google/otp_window 60


/workspaces/warden/bin/warden env exec -T php-fpm bin/magento cache:flush