name: Mage-OS Setup in Warden
run-name: ${{ github.actor }} is running Mage-OS Setup in warden
on:
  workflow_dispatch: { }
  push:
    branches:
      - feature/magento-setup*

permissions:
  contents: write

jobs:
  matrix-calculator:
    runs-on: ubuntu-latest
    outputs:
      php_versions: ${{ steps.set-matrix.outputs.php_versions }}
      database_versions: ${{ steps.set-matrix.outputs.database_versions }}
      search_versions: ${{ steps.set-matrix.outputs.search_versions }}
      message_queue_versions: ${{ steps.set-matrix.outputs.message_queue_versions }}
      cache_versions: ${{ steps.set-matrix.outputs.cache_versions }}
      http_cache_versions: ${{ steps.set-matrix.outputs.http_cache_versions }}
    steps:
      - name: Checkout PR commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - id: set-matrix
        name: Calculate Matrix
        run: |
          echo "php_versions=$(jq -c .services.php supported-services.json)" >> "$GITHUB_OUTPUT"
          echo "database_versions=$(jq -c .services.database supported-services.json)" >> "$GITHUB_OUTPUT"
          echo "search_versions=$(jq -c .services.search supported-services.json)" >> "$GITHUB_OUTPUT"
          echo "message_queue_versions=$(jq -c .services.message_queue supported-services.json)" >> "$GITHUB_OUTPUT"
          echo "cache_versions=$(jq -c .services.cache supported-services.json)" >> "$GITHUB_OUTPUT"
          echo "http_cache_versions=$(jq -c .services.http_cache supported-services.json)" >> "$GITHUB_OUTPUT"
      - name: Debug output
        run: |
          echo "PHP Versions: ${{ steps.set-matrix.outputs.php_versions }}"
          echo "database Versions: ${{ steps.set-matrix.outputs.database_versions }}"
          echo "search Versions: ${{ steps.set-matrix.outputs.search_versions }}"
          echo "message_queue Versions: ${{ steps.set-matrix.outputs.message_queue_versions }}"
          echo "cache Versions: ${{ steps.set-matrix.outputs.cache_versions }}"
          echo "http_cache Versions: ${{ steps.set-matrix.outputs.http_cache_versions }}"

  mage-os-setup-run:
    runs-on: ubuntu-latest
    needs: [matrix-calculator]
    strategy:
      fail-fast: false
      matrix:
        php_version: ${{ fromJSON(needs.matrix-calculator.outputs.php_versions) }}
        database_version: ${{ fromJSON(needs.matrix-calculator.outputs.database_versions) }}
        search_version: ${{ fromJSON(needs.matrix-calculator.outputs.search_versions) }}
        message_queue_version: ${{ fromJSON(needs.matrix-calculator.outputs.message_queue_versions) }}
        cache_version: ${{ fromJSON(needs.matrix-calculator.outputs.cache_versions) }}
        http_cache_version: ${{ fromJSON(needs.matrix-calculator.outputs.http_cache_versions) }}
    steps:
      - name: Debug output
        run: |
          echo "PHP Versions: ${{ matrix.php_version }}"
          echo "database Versions: ${{ matrix.database_version }}"
          echo "search Versions: ${{ matrix.search_version }}"
          echo "message_queue Versions: ${{ matrix.message_queue_version }}"
          echo "cache Versions: ${{ matrix.cache_version }}"
          echo "http_cache Versions: ${{ matrix.http_cache_version }}"

      - name: Checkout PR commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: main
          fetch-depth: 0

      - name: Setup Mage-OS
        uses: ./main/.github/action/setup-mage-os
        with:
          database: ${{ matrix.database_version }}
          search: ${{ matrix.search_version }}
          varnish: ${{ matrix.http_cache_version }}
          rabbitmq: ${{ matrix.message_queue_version }}
          redis: ${{ matrix.cache_version }}
          run_setup_install: "1"
          run_setup_upgrade: "1"
          run_reindex: "1"
          run_production_deploy_mode: "1"
          run_magento_config_preset: "1"
          run_admin_user_creation: "1"
