name: magento-setup-warden
run-name: ${{ github.actor }} is running magento setup in warden
on:
  workflow_dispatch: { }
  push:
    branches:
      - feature/magento-setup*

permissions:
  contents: write

jobs:
  magento-setup-warden:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: main
          fetch-depth: 0

      - name: Setup Mage-OS
        uses: ./main/.github/action/setup-mage-os
