name: Integration Tests (test?)
on:
  workflow_call:
    inputs:
      run_memory_test:
        type: boolean
        description: Run memory tests?
        required: true
        default: true
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "yo!: {inputs.run_memory_test}"
