name: Unit Tests
run-name: ${{ github.actor }} is running Unit Tests
on:
  pull_request:
    branches:
      - 2.4-develop
      - nx-unit-testing

permissions:
  contents: write

jobs:
  run-unit-tests:
    uses: adamzero1/mage-os-infrastructure/.github/workflows/unit-tests.yml@nx-unit-testing
    